export const properties = [
  {
    id: 1,
    title: "Luxury Modern Villa",
    location: "Himagiri Meadows, Bangalore",
    price: "2.5 Cr",
    bedrooms: 4,
    bathrooms: 3,
    area: "3500 sq.ft",
    type: "Villa",
    featured: true,
    image: "/images/property-1.jpg",
    description: "Stunning modern villa with contemporary architecture, smart home features, and private garden."
  },
  {
    id: 2,
    title: "Premium Apartment",
    location: "MLA Layout, Bangalore",
    price: "1.8 Cr",
    bedrooms: 3,
    bathrooms: 2,
    area: "2200 sq.ft",
    type: "Apartment",
    featured: true,
    image: "/images/property-2.jpg",
    description: "High-end apartment with panoramic city views, premium finishes, and excellent amenities."
  },
  {
    id: 3,
    title: "Spacious Penthouse",
    location: "Gottigere, Bangalore",
    price: "3.2 Cr",
    bedrooms: 4,
    bathrooms: 4,
    area: "4000 sq.ft",
    type: "Penthouse",
    featured: true,
    image: "/images/property-3.jpg",
    description: "Exclusive penthouse with rooftop access, luxury interiors, and state-of-the-art amenities."
  },
  {
    id: 4,
    title: "Garden House",
    location: "Bangalore East",
    price: "2.1 Cr",
    bedrooms: 3,
    bathrooms: 3,
    area: "3000 sq.ft",
    type: "Villa",
    featured: true,
    image: "/images/property-4.jpg",
    description: "Beautiful house with lush gardens, modern architecture, and natural light throughout."
  },
  {
    id: 5,
    title: "Smart Home Complex",
    location: "South Bangalore",
    price: "1.5 Cr",
    bedrooms: 2,
    bathrooms: 2,
    area: "1800 sq.ft",
    type: "Apartment",
    featured: true,
    image: "/images/property-5.jpg",
    description: "Intelligent home with automation, energy-efficient design, and modern amenities."
  },
  {
    id: 6,
    title: "Elegant Bungalow",
    location: "Premium Location",
    price: "2.8 Cr",
    bedrooms: 4,
    bathrooms: 3,
    area: "3800 sq.ft",
    type: "Villa",
    featured: true,
    image: "/images/property-6.jpg",
    description: "Classic elegant bungalow with timeless design, mature landscaping, and peaceful ambiance."
  },
  {
    id: 7,
    title: "Modern Studio",
    location: "City Center",
    price: "85 Lakhs",
    bedrooms: 1,
    bathrooms: 1,
    area: "900 sq.ft",
    type: "Apartment",
    featured: false,
    image: "/images/property-7.jpg",
    description: "Contemporary studio apartment perfect for professionals, well-designed and efficient."
  },
  {
    id: 8,
    title: "Investment Property",
    location: "Emerging Area",
    price: "1.2 Cr",
    bedrooms: 2,
    bathrooms: 2,
    area: "1600 sq.ft",
    type: "Apartment",
    featured: false,
    image: "/images/property-8.jpg",
    description: "Excellent investment opportunity in a rapidly developing locality with high appreciation."
  },
]
